#pragma once
#include <Arduino.h>

// services/AirportDB — reads the LittleFS airport + radio-frequency table
// (/airports.bin, generated by tools/gen_airports.py) and finds the nearest field to
// the observer with its likely frequencies. File-backed so the ~80 KB table lives in
// LittleFS rather than flash .rodata. The nearest result is cached until the observer
// moves materially, so the file is scanned only on demand (not per frame).
class AirportDB {
public:
  static constexpr int kMaxFreq = 12;
  struct Nearest {
    bool     valid = false;
    char     id[5] = {0};               // null-terminated ident
    float    distNm = 0, brgDeg = 0;
    uint8_t  n = 0;                      // frequency count
    uint8_t  type[kMaxFreq];            // type codes -> label()
    uint16_t f40[kMaxFreq];            // MHz * 40
  };

  bool begin(const char* path = "/airports.bin");
  bool ready() const { return _ok; }
  const Nearest& nearest(double latDeg, double lonDeg);   // cached between moves
  static const char* label(uint8_t code);                 // freq type label

private:
  bool _ok = false;
  String _path;
  uint32_t _nA = 0, _nF = 0, _recBase = 0, _typeBase = 0, _f40Base = 0;
  double _lat = 999, _lon = 999;
  Nearest _near;
};
