#pragma once
#include <Arduino.h>
#include <FS.h>

// services/AirportDB — reads the LittleFS airport + radio-frequency table
// (/airports.bin, generated by tools/gen_airports.py) and finds the nearest field to
// the observer with its likely frequencies. File-backed so the ~80 KB table lives in
// LittleFS rather than flash .rodata. The nearest result is cached until the observer
// moves materially, so the file is scanned only on demand (not per frame).
class AirportDB {
public:
  static constexpr int kMaxFreq = 12;
  struct Nearest {
    bool     valid = false;
    char     id[5] = {0};               // null-terminated ident
    float    distNm = 0, brgDeg = 0;
    uint8_t  n = 0;                      // frequency count
    uint8_t  type[kMaxFreq];            // type codes -> label()
    uint16_t f40[kMaxFreq];            // MHz * 40
  };

  bool begin(const char* path = "/airports.bin");
  bool ready() const { return _ok; }
  const Nearest& nearest(double latDeg, double lonDeg);             // closest field
  const Nearest& byId(const char* icao, double obsLat, double obsLon);  // a specific field
  static const char* label(uint8_t code);                          // freq type label

private:
  void load(File& f, const uint8_t* id4, int16_t lat100, int16_t lon100,
            uint16_t fOff, uint8_t fCnt, double obsLat, double obsLon);  // fill _near
  bool _ok = false;
  String _path, _key;                    // _key caches the last query (loc or ident)
  uint32_t _nA = 0, _nF = 0, _recBase = 0, _typeBase = 0, _f40Base = 0;
  Nearest _near;
};
